name: Build and Deploy

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 19
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
      - name: Build Project
        run: |
          npm i
          npm run build
          cp build/index.html build/404.html
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
